# Generated by Django 2.2.7 on 2019-12-04 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nif', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=70)),
                ('phone_number', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=40)),
                ('web_adress', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField()),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Tag_nfc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('identify', models.CharField(max_length=255)),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_bag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Register_activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('tag_nfc', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Tag_nfc')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('product', models.ManyToManyField(blank=True, to='backend.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Publicity_campaign',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('description', models.TextField()),
                ('company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Company')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='publicity_campaing',
            field=models.ManyToManyField(blank=True, to='backend.Publicity_campaign'),
        ),
    ]
