# Generated by Django 2.2.7 on 2020-01-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_publicity_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity_campaign',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
