# Generated by Django 2.2.7 on 2020-01-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20200127_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile_image/profile_default.png', upload_to='profile_image'),
        ),
    ]
