# Generated by Django 2.2.7 on 2020-01-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20200127_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicity_campaign',
            name='image',
            field=models.ImageField(blank=True, upload_to='publicity_campaign_image'),
        ),
    ]
