# Generated by Django 2.2.7 on 2020-01-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_publicity_campaign_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicity_campaign',
            name='user',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
