# Generated by Django 2.2.7 on 2020-02-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_publicity_campaign_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='publicity_campaing',
        ),
        migrations.AddField(
            model_name='publicity_campaign',
            name='publicity_campaing',
            field=models.ManyToManyField(blank=True, to='backend.Product'),
        ),
    ]
