# Generated by Django 2.2.7 on 2020-02-07 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20200206_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicity_campaign',
            old_name='publicity_campaing',
            new_name='product',
        ),
    ]
