# Generated by Django 3.0.3 on 2020-02-11 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20200207_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
    ]
