# Generated by Django 3.0.3 on 2020-02-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('peso', 'PESO'), ('litros', 'LITRO'), ('unidad', 'UNIDAD')], default='unidad', max_length=6),
        ),
    ]
