# Generated by Django 3.0.3 on 2020-02-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('litros', 'Litro'), ('unidad', 'Unidad')], default='Unidad', max_length=6),
        ),
    ]
