# Generated by Django 3.0.3 on 2020-02-11 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_auto_20200211_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('available', models.BooleanField(default=True, null=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogramo'), ('litros', 'Litro'), ('unidad', 'Unidad')], default='Unidad', max_length=6)),
                ('user', models.CharField(blank=True, max_length=40)),
                ('image', models.ImageField(blank=True, upload_to='product_image')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Product')),
            ],
        ),
    ]
