# Generated by Django 3.0.3 on 2020-02-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_product_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='picture',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_image'),
        ),
    ]
