# Generated by Django 3.0.3 on 2020-02-14 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0030_auto_20200213_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
