# Generated by Django 3.0.3 on 2020-03-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_auto_20200301_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity_campaign',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='products', to='backend.Product'),
        ),
    ]
