# Generated by Django 3.0.3 on 2020-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0034_auto_20200301_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicity_campaign',
            name='product',
            field=models.ManyToManyField(blank=True, to='backend.Product'),
        ),
    ]
