# Generated by Django 3.0.3 on 2020-03-10 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0036_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_nfc',
            name='date_end',
        ),
        migrations.RemoveField(
            model_name='tag_nfc',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='tag_nfc',
            name='identify',
        ),
        migrations.AddField(
            model_name='tag_nfc',
            name='publicity_campaign',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Publicity_campaign'),
        ),
    ]
