# Generated by Django 3.0.3 on 2020-03-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0037_auto_20200310_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_nfc',
            name='available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
