# Generated by Django 3.0.3 on 2020-03-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0039_auto_20200311_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag_nfc',
            name='offer',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
