# Generated by Django 3.0.3 on 2020-03-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0040_auto_20200311_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_nfc',
            name='description',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
