# Generated by Django 3.0.3 on 2020-05-14 09:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0043_point_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
