# Generated by Django 3.0.3 on 2020-08-24 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0048_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='name1',
        ),
    ]
