# Generated by Django 3.0.3 on 2020-08-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0049_auto_20200824_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
