# Generated by Django 3.0.3 on 2020-08-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0053_auto_20200824_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag_nfc',
            name='latitude',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='tag_nfc',
            name='longitude',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
