# Generated by Django 3.0.3 on 2020-08-25 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0055_auto_20200825_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='latitude',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='point',
            name='longitude',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
