# Generated by Django 3.1 on 2020-08-26 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0056_auto_20200825_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_activity',
            name='tag_nfc',
        ),
        migrations.AddField(
            model_name='register_activity',
            name='city',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='country_name',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='ip_address',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='region_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
