# Generated by Django 3.1 on 2020-08-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0057_auto_20200826_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_activity',
            name='activity',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
