# Generated by Django 3.1 on 2020-08-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0059_register_activity_publicity_campaign_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register_activity',
            old_name='publicity_campaign_name',
            new_name='activity_name',
        ),
    ]
