# Generated by Django 3.1 on 2020-08-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0061_auto_20200828_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_activity',
            name='publicity_campaign_date_end',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='publicity_campaign_date_start',
            field=models.DateField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='publicity_campaign_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='publicity_campaign_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
