# Generated by Django 3.1 on 2020-08-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0062_auto_20200828_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_activity',
            name='recipe_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
