# Generated by Django 3.1 on 2020-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0063_register_activity_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_description',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_latitude',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_longitude',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_product',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_publicity_campaign',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
