# Generated by Django 3.1 on 2020-08-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0064_auto_20200829_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_activity',
            name='tag_id',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
