# Generated by Django 3.1 on 2020-08-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0065_register_activity_tag_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_activity',
            name='tag_nfc_available',
        ),
        migrations.AddField(
            model_name='register_activity',
            name='tag_nfc_status',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
