# Generated by Django 3.1 on 2020-08-29 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0066_auto_20200829_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_activity',
            name='tag_nfc_publicity_campaign',
        ),
    ]
