# Generated by Django 2.2.12 on 2020-11-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0067_remove_register_activity_tag_nfc_publicity_campaign'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Shopping_bag',
        ),
    ]
